language: python
python:
  - 2.7
  - 3.4
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U pip wheel
  - pip install -r test-requirements.txt
  - pip install -e .
script:
  - spreadflow-twistd -n -o -c tutorial/001-observing-directories/spreadflow.conf
  - spreadflow-twistd -n -o -c tutorial/002-duplicate-and-filter/spreadflow.conf
  - spreadflow-twistd -n -o -c tutorial/003-loadfile-computed-value/spreadflow.conf
  - spreadflow-twistd -n -o -c tutorial/004-mapreduce/spreadflow.conf
